apiVersion: v1
kind: ServiceAccount
metadata:
  name: sync-groups
  namespace: cozy-keycloak

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-access
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-access-binding
subjects:
  - kind: ServiceAccount
    name: sync-groups
    namespace: cozy-keycloak
roleRef:
  kind: ClusterRole
  name: namespace-access
  apiGroup: rbac.authorization.k8s.io
